# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 3306
  database: rails_mind_app_development
  username: root
  password: 123456

test:
  <<: *default
  database: rails_mind_app_test

production:
  <<: *default
  database: rails_mind_app_production
  username: rails_mind_app
  password: <%= ENV['RAILS_MIND_APP_DATABASE_PASSWORD'] %>
